### ISSUE TITLE
[BUG] url re-direction after login does not work

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/security-dashboards-plugin#926]
**Describe the bug**

A qualified / saved URL for a plugin or visualization etc. after login fails to redirect the user, instead he user is sent to the home page

**To Reproduce**
1. open a saved url from new browser session
2. post login, instead of the url resource; the user is sent to the home

**Comment by DarshitChanpura** [comment]
@anirudha can you share what the url looks like when it is on login screen?

**Comment by peternied** [comment]
@anirudha We just pushed fix around url redirection, there is a high likelyhood that this issue was resolved.  When the 2.0.0 release is available could you double check your scenario?

I'll update this issue when we have a docker image that contains this fix

**Comment by peternied** [comment]
@anirudha RC image is available, see https://github.com/opensearch-project/opensearch-build/issues/1624#issuecomment-1105736225

We will close this issue assuming the problem has been resolved.

**Comment by ibrambe** [comment]
@peternied I have this issue with the 2.0.0 release. Authentication via OpenID, hash got lost after login.

**Comment by kavilla** [comment]
@peternied based on @ibrambe this still seems to be an issue with the `2.0.0` release. Also, will the fix for re-direct be backported to a `1.x` or has been backported already?

**Comment by ibrambe** [comment]
Indeed, this is not fixed yet.
#831 + #1001 are related to this same problem.

**Comment by boehb-efs** [comment]
I'm guessing, instead of going directly to the basepath, you should go to /app/home#/. 
In the AuthenticationType implementations, nexturl is only assembled if isPageRequest is true (path contains /app/ or /goto/).

**Comment by ahopp** [comment]
@peternied @davidlago Can we open this ticket back up and see what we can do to resolve? Or should we track the new here: https://github.com/opensearch-project/security-dashboards-plugin/issues/831?

**Comment by davidlago** [comment]
Is this still happening after 2.2? it looks like it did go out in that version https://github.com/opensearch-project/security-dashboards-plugin/pull/1054

**Comment by Martin-Kemp** [comment]
> I'm guessing, instead of going directly to the basepath, you should go to /app/home#/.
In the AuthenticationType implementations, nexturl is only assembled if isPageRequest is true (path contains /app/ or /goto/).

I'm also experiencing behavior like this. Except I'm not even able to log in if the login url does not contain `/app/home`. We're currently upgrading from `1.2.3` to `2.4` and OIDC was working correctly in `1.2.3`. There are some other changes with our config as well though, like using https instead of http on port 9200.

**Comment by cwperks** [comment]
@Martin-Kemp There was a change included in 2.5.0 that resolved an issue with OIDC redirect.

Link to PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/1282
Link to original issue: https://github.com/opensearch-project/security-dashboards-plugin/issues/1098

Does this fix resolve the issue you are facing?

**Comment by Martin-Kemp** [comment]
Thanks for the quick reply @cwperks . That PR looks very promising, I'll test it and report back.

**Comment by Martin-Kemp** [comment]
@cwperks I can confirm this works in 2.5. Thanks!

**Comment by cwperks** [comment]
@Martin-Kemp Thank you for confirming! :)

**Comment by Rockhard80** [comment]
This looks again broken in 2.13 and OIDC (Keycloak).
I can reproduce it with:

1. Navigate to any dashboards and save the url
2. Log out
3. Paste the url in the browser
4. After login, instead of the dashboard indicated by the url, the user is sent to the dashboards home.

Following the indication found in this [discussion](https://forum.opensearch.org/t/osd-dashboard-url-redirection-fails-for-the-first-time-in-safari-browser-and-load-the-dashboard-lists-page-instead-of-specific-dashboard/15609/2) , I have tried to use the "short URL" from the Share->Permalink button, and it works indeed. 

So while there is a workaround, the actual expected behavior appears to be broken.

**Comment by cwperks** [comment]
@Rockhard80 Are you using a basePath? There is a known issue with basePaths in 2.13 that is planned to be resolved in 2.15: https://github.com/opensearch-project/security-dashboards-plugin/pull/1899

**Comment by Rockhard80** [comment]
thx  @cwperks , but I'm not using basePath. 
I have only the base_redirect_url in place, which points to the server root URL (i.e. https://myOpenSearch.my.test.com).
Besides that, the following ones are commented out (i.e. default values):

#server.basePath: ""
# server.name: "your-hostname"
#server.rewriteBasePath: false
